name: Trip Cron Test

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  run-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call script
        run: curl -A "Mozilla/5.0" https://TUDOMINIO.infinityfreeapp.com/check_trips.php?token=123

